name: ci

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  frontend-unit-tests:
    runs-on: ubuntu-latest
    steps:   
      - name: "Start Frontend"
        run: |
          cd frontend &&
          npm install &&
          npm run build &&
          npm run start &
          sleep 5 &&
          curl http://localhost:3333 -I
  api-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: "Start Backend"
        run: |
          cd server &&
          npm install &&
          npm run build &&
          npm run start:prod &
          sleep 5 &&
          curl http://localhost:3333 -I
  